[workspace]

members = [
    "medic-step-git",
    "medic-step-github",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.1.8" }
clap_complete = "4.1.4"
indoc = "2.0.1"
regex = "1.7"
serde = { version = "1.0" }
serde_json = "1.0"
toml = "0.7"
